[project]
name = "clean_energy_statistics"
description = "Visualization of clean energy build rates per capita"
version = "0.1.0"
authors = [
  { name = "Sampo Smolander", email = "sampo.smolander@kapsi.fi" }
]
dependencies = [
  "pandas>=2.0",
  "openpyxl",
  "pycountry",
  "requests",
]
